name: plantuml-server
services:
  plantuml-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 8080
      published: "8080"
      protocol: tcp
networks:
  default:
    name: plantuml-server_default
